"""Integracion de tabla usuario

Revision ID: 7babdfee57fd
Revises: 61ee0aff6c5a
Create Date: 2026-05-19 00:47:26.309750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7babdfee57fd'
down_revision: Union[str, Sequence[str], None] = '61ee0aff6c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
